version: '2'

services:
  apache:
    container_name: revealjs
    image: 'bitnami/apache:latest'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app
    volumes:
      - 'apache_data:/bitnami/apache'
      - './public_html:/app'
      - './vhosts:/bitnami/apache/conf/vhosts'
volumes:
  apache_data:
    driver: local
    
networks:
  default:
    driver: bridge
  app:
    driver: bridge